### ISSUE TITLE
Visual Studio Unreachable code detected

### ISSUE THREAD

**Issue by CloudLing20** [MrAfitol/Lobby#2]
Visual Studio found Unreachable code detected on lines 200 and 259 in the EventHandlers.cs file.
I don't know if this will affect the plug-in, I just told you that there is a problem.

**Comment by MrAfitol** [comment]
I don't know why I left it in the code, it's not necessary, I'll remove it

**Comment by MrAfitol** [comment]
It was supposed to be a function for height adjustment, but I believe that it is not needed here
