### ISSUE TITLE
The server reported a fatal error

### ISSUE THREAD

**Issue by CloudLing20** [MrAfitol/Lobby#3]
Error content:
[Error] [PluginAPI] Event OnThrowItem (PlayerThrowItem) in plugin Lobby.Lobby contains wrong parameters
- Player, ItemBase, Rigidbody
- Required:
- IPlayer, ItemBase.
This will cause players to leave the game range when spawning.
I'm not sure if other people have this problem, but I encountered this fatal error.

**Comment by MrAfitol** [comment]
What version of PluginAPI are you using?

**Comment by MrAfitol** [comment]
From version 1.0.6 you must use PluginAPI 12.0.0-rc.6

**Comment by CloudLing20** [comment]
The server is the latest version

**Comment by CloudLing20** [comment]
> 从版本 1.0.6 开始，您必须使用 PluginAPI 12.0.0-rc.6

The server is the latest version

**Comment by CloudLing20** [comment]
> 从版本 1.0.6 开始，您必须使用 PluginAPI 12.0.0-rc.6

12.0.0-rc.6 should be used

**Comment by MrAfitol** [comment]
Strange, check PluginAPI.dll

> > 从版本 1.0.6 开始，您必须使用 PluginAPI 12.0.0-rc.6
> 
> The server is the latest version

**Comment by CloudLing20** [comment]
[PluginAPI.zip](https://github.com/MrAfitol/Lobby/files/10344885/PluginAPI.zip)
This is the NWPlugin.dll of the server. In fact, I mean, it is the latest server version, not the latest NWPlugin.dll

**Comment by CloudLing20** [comment]
> 奇怪，查看PluginAPI.dll
> 
> > > 从版本1.0.6开始，您必须使用PluginAPI 12.0.0-rc.6
> > 
> > 
> > 服务器是最新版本

[PluginAPI.zip](https://github.com/MrAfitol/Lobby/files/10344885/PluginAPI.zip)
This is the NWPlugin.dll of the server. In fact, I mean, it is the latest server version, not the latest NWPlugin.dll

**Comment by CloudLing20** [comment]
> 奇怪，查看PluginAPI.dll
> 
> > > 从版本1.0.6开始，您必须使用PluginAPI 12.0.0-rc.6
> > 
> > 
> > 服务器是最新版本

I'm not sure the latest server version is compatible with this.

**Comment by MrAfitol** [comment]
Your version is 12.0.0-rc.5, but it should be 12.0.0-rc.6, please update it

**Comment by CloudLing20** [comment]
> Your version is 12.0.0-rc.5, but it should be 12.0.0-rc.6, please update it

Encountered new problems after the update
Error content:
[Error] [Lobby] [Lobby] [Event: OnRoundStarted] System.TypeLoadException: Could not resolve type with token 010000cc (from typeref, class/assembly PlayerRoles.RoleSpawnFlags, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
                                   at Lobby.EventHandlers.OnRoundStarted () [0x00026] in <34d7e6ee7af448f2a94c8b796429ff34>:0

**Comment by CloudLing20** [comment]
> Your version is 12.0.0-rc.5, but it should be 12.0.0-rc.6, please update it

It seems that it cannot be updated directly, and it needs to wait for the developer to update.

**Comment by MrAfitol** [comment]
> > Your version is 12.0.0-rc.5, but it should be 12.0.0-rc.6, please update it
> 
> Encountered new problems after the update Error content: [Error] [Lobby] [Lobby] [Event: OnRoundStarted] System.TypeLoadException: Could not resolve type with token 010000cc (from typeref, class/assembly PlayerRoles.RoleSpawnFlags, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null) at Lobby.EventHandlers.OnRoundStarted () [0x00026] in <34d7e6ee7af448f2a94c8b796429ff34>:0

How did you update? PluginAPI replacement file?

**Comment by CloudLing20** [comment]
> > > Your version is 12.0.0-rc.5, but it should be 12.0.0-rc.6, please update it
> > 
> > 
> > Encountered new problems after the update Error content: [Error] [Lobby] [Lobby] [Event: OnRoundStarted] System.TypeLoadException: Could not resolve type with token 010000cc (from typeref, class/assembly PlayerRoles.RoleSpawnFlags, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null) at Lobby.EventHandlers.OnRoundStarted () [0x00026] in <34d7e6ee7af448f2a94c8b796429ff34>:0
> 
> How did you update? PluginAPI replacement file?

Indeed, I don't know how to update it

**Comment by MrAfitol** [comment]
It is necessary to update through steamcmd `app_update 996560 -beta pluginapi-beta validate
`

**Comment by MrAfitol** [comment]
This is indicated by the developers in the **announcement** chat discord

**Comment by CloudLing20** [comment]
Thank
